POST http://localhost:3333/tasks
Content-Type: "application/json"

{
  "title":"Task test",
  "description":"Description test"
}

###

GET http://localhost:3333/tasks

###

DELETE http://localhost:3333/tasks/bd1d4947-577e-4f99-bd51-bd029f00f4ac9

###

PUT http://localhost:3333/tasks/5f6b7615-284c-4f9e-ac28-670486c06d0c9
Content-Type: "application/json"

{
  "title":"Testando ",
  "description": "Update description test"
}

###

PATCH http://localhost:3333/tasks/5f6b7615-284c-4f9e-ac28-670486c06d0c/complete
