POST http://localhost:3333/tasks
Content-Type: "application/json"

{
  "title":"Task test",
  "description":"Description test"
}

###

GET http://localhost:3333/tasks

###

DELETE http://localhost:3333/tasks/91e95c16-0892-40c3-bcd4-736f9b5dd64d

###

PUT http://localhost:3333/tasks/84d6dce0-998b-4099-bfb7-03bb3ca41b78
Content-Type: "application/json"

{
  "title":"Testando ",
  "description": "Update description test"
}

###

PATCH http://localhost:3333/tasks/84d6dce0-998b-4099-bfb7-03bb3ca41b78/complete
