POST http://localhost:3333/users
Content-Type: "application/json"

{
  "name":"rafael neves",
  "email":"rafaelneves@gmail.com"
}

###

GET http://localhost:3333/users?search=rafael

###

DELETE http://localhost:3333/users/146eb60f-8234-4e30-856b-9dc77f5d8f7f

###

PUT http://localhost:3333/users/3509d18b-695d-4ddf-818c-c6e60305cc50
Content-Type: "application/json"

{
  "name": "john doe",
  "email": "johndoe@gmail.com"
}